# numpy are faster than lists
# they utilise contigouus memory 
# there is inertion, deletion, appending and concatenation and lots more
# its a mathematics( MATLAB CALCULATION)
# plotting - matplotblib
# backend - pandas
# machine learning: tensors connected to numpy libraries

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,4])
a
print(a)

[1 2 4]


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8]], dtype='float64')
b

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [6]:
# dimensions
print(a.ndim)
print(b.ndim)

1
2


In [7]:
# shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [8]:
# type (4 bytes for int 32)
a.dtype

dtype('int32')

In [9]:
# get size (4 bytes for int 32)
a.itemsize

4

In [10]:
# total size
a.nbytes

12

In [11]:
# size or number of elements
a.size

3

In [12]:
# totol size
a.size * a.itemsize

12

In [13]:
b.dtype

dtype('float64')

In [14]:
b.nbytes

64

In [15]:
b.itemsize

8

In [16]:
b.size

8

In [17]:
# get specific element
b[1,1]

6.0

In [18]:
# get a specific row
b[1, :]

array([5., 6., 7., 8.])

In [19]:
# get a specific column
b[:, 3]

array([4., 8.])

In [23]:
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [24]:
# start index, end index, step
b[1, 0:3:2]

array([5., 7.])

### 3-d numpy

In [25]:
c = np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])
print(c)
print(c.shape)
print(c.size)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
8
3


In [26]:
# get specific elements
c[0,1,1]

4

## different types of arrays

In [28]:
# all zero matrix
one_dim = np.zeros((2,2,2))
print(one_dim)
print(one_dim.ndim)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [31]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [32]:
two_dim = np.zeros((2,3))
print(two_dim)
print(two_dim.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2


In [33]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
three_dim = np.ones((2,2,3))
print(three_dim)
print(three_dim.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
3


In [41]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [42]:
a.shape

(3,)

In [43]:
full = np.full_like(a.shape,4)
print(a)
print(a.shape)
print(full)

[1 2 4]
(3,)
[4]


In [45]:
a

array([1, 2, 4])

In [44]:
np.full_like(a, 4)

array([4, 4, 4])

In [47]:
#random decimal numbers
random = np.random.rand(4,4)
random

array([[0.75069073, 0.13946602, 0.78489169, 0.14241901],
       [0.43429611, 0.83088675, 0.96788145, 0.18052542],
       [0.48137149, 0.40220453, 0.7096623 , 0.71747796],
       [0.34392043, 0.47381272, 0.32616516, 0.81961239]])

In [55]:
rand_1 = random.reshape(-1,)
print(rand_1)
print()
print(rand_1.shape)
print(rand_1.ndim)

[0.75069073 0.13946602 0.78489169 0.14241901 0.43429611 0.83088675
 0.96788145 0.18052542 0.48137149 0.40220453 0.7096623  0.71747796
 0.34392043 0.47381272 0.32616516 0.81961239]

(16,)
1


In [58]:
rand_2 = random.reshape(-1,1)
print(rand_2)
print()
print(rand_2.shape)
print(rand_2.ndim)

[[0.75069073]
 [0.13946602]
 [0.78489169]
 [0.14241901]
 [0.43429611]
 [0.83088675]
 [0.96788145]
 [0.18052542]
 [0.48137149]
 [0.40220453]
 [0.7096623 ]
 [0.71747796]
 [0.34392043]
 [0.47381272]
 [0.32616516]
 [0.81961239]]

(16, 1)
2


In [59]:
np.random.random_sample(a.shape)

array([0.13226443, 0.45296383, 0.8173595 ])

In [107]:
# random integer values
np.random.randint(7, size=(3,3))

array([[2, 5, 4],
       [0, 4, 4],
       [6, 6, 6]])

In [63]:
np.random.randint((2,3), 7)

array([3, 4])

In [77]:
np.random.randint(5, size = (3,3))

array([[0, 2, 2],
       [2, 2, 3],
       [0, 0, 2]])

In [78]:
np.random.rand((5))

array([0.26035572, 0.68895158, 0.03034696, 0.18294922, 0.70037516])

In [79]:
np.random.rand(3,3)

array([[0.17542471, 0.54982852, 0.74488866],
       [0.86551128, 0.14621252, 0.36675705],
       [0.07613342, 0.45666167, 0.73144918]])

In [80]:
np.random.randint(3,7, size=(3,3))

array([[3, 5, 6],
       [5, 6, 4],
       [3, 6, 5]])

In [81]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
# repeat array
arr = np.array([[1,2,3]])
ri = np.repeat(arr, 3, axis=1)
print(ri)

[[1 1 1 2 2 2 3 3 3]]


In [83]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
# copy
a = np.array([8,9,7])
b = a.copy()
b[1] = 4
print(a)
print(b)

[8 9 7]
[8 4 7]


## maths

In [85]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [86]:
a - 2

array([-1,  0,  1])

In [87]:
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [88]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

#### Linear Algebra

In [89]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# find determinant
c = np.identity(2)
print(c)
print(np.linalg.det(c))
print(np.trace(c))

[[1. 0.]
 [0. 1.]]
1.0
2.0


In [95]:
# determinant
# trace
# singular vector decomposition
# eignen values
# matrix form
# inverse

##### Statistics

In [96]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
print(stats.nbytes)
print(stats.itemsize)
print(stats.size)
print(stats.shape)
print(stats.ndim)

[[1 2 3]
 [4 5 6]]
24
4
6
(2, 3)
2


In [97]:
print(stats)
axis_one = np.min(stats, axis=1)
print(axis_one)
axis_two = np.max(stats, axis=0)
print(axis_two)

[[1 2 3]
 [4 5 6]]
[1 4]
[4 5 6]


In [98]:
np.max(stats)

6

In [99]:
print(stats)
print()
axis_zero = np.sum(stats, axis=0)
print(axis_zero)
print()
axis_one = np.sum(stats, axis=1)
print(axis_one)

[[1 2 3]
 [4 5 6]]

[5 7 9]

[ 6 15]


### reorganizing array

In [101]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [102]:
before.reshape(-1,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
# before.reshape(1,)

In [106]:
before.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [107]:
before.shape

(2, 4)

In [108]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print()
print(np.vstack([v1,v2,v2]))
print()
print(np.vstack([v1,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [109]:
# horizontally stacking vectors
h1 = np.ones((2,4), dtype='int32')
h2 = np.zeros((2,2), dtype='int32')
print(h1)
print()
print(h2)
print()
print(np.hstack([h1,h2]))
print()
print(np.hstack([h1,h2,h1]))

[[1 1 1 1]
 [1 1 1 1]]

[[0 0]
 [0 0]]

[[1 1 1 1 0 0]
 [1 1 1 1 0 0]]

[[1 1 1 1 0 0 1 1 1 1]
 [1 1 1 1 0 0 1 1 1 1]]


In [123]:
ram = np.array([1, 2, 3], dtype='int64')
ram

array([1, 2, 3], dtype=int64)

In [124]:
ram.itemsize

8

In [125]:
ram.size

3

### get data from file

In [127]:
# # delimiter presents the separator 
# filedata = np.genfromtxt('data.text', delimiter=',') # from notepad/file

# # convert into integer as the text is in floats
# filedata.astype('int32')


In [128]:
# # boolean masking and advanced indexing
# filedata > 50  # will  give boolean values whether true or false

# # index where the file is greater than 50
# filedata[filedata>50]

In [132]:
# indexing with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,4,5]]

array([1, 5, 6])

In [135]:
# if any of the values in a were greater than 6
np.any(a>6)

True

In [138]:
np.all(a>3)

False

In [139]:
((a>3) & (a<8))

array([False, False, False,  True,  True,  True,  True, False, False])

## numpy strings

In [140]:
# concatenate elementwise to arrays of strings
a = np.array([['python ', 'Java ']])
b = np.array([['PHP', 'C++']])
c = np.char.add(a, b)
print(c)

[['python PHP' 'Java C++']]


In [141]:
# repeat items in an array
a = np.array([['Python', 'PHP', 'Java', 'C++']])
b = np.repeat(a,3)
b

array(['Python', 'Python', 'Python', 'PHP', 'PHP', 'PHP', 'Java', 'Java',
       'Java', 'C++', 'C++', 'C++'], dtype='<U6')

In [142]:
# repeat items
a = np.array([['Python', 'PHP', 'Java', 'C++']])
b = np.char.multiply(a,3)
b

array([['PythonPythonPython', 'PHPPHPPHP', 'JavaJavaJava', 'C++C++C++']],
      dtype='<U18')

In [143]:
# lower and upper cases
a = np.array([['python', 'Php', 'Java', 'C++']])
upper = np.char.upper(a)
lower = np.char.lower(a)
title = np.char.title(a)
capitalize = np.char.capitalize(a)
swapcase = np.char.swapcase(a)
print(upper)
print(lower)
print(title)
print(capitalize)
print(swapcase)

[['PYTHON' 'PHP' 'JAVA' 'C++']]
[['python' 'php' 'java' 'c++']]
[['Python' 'Php' 'Java' 'C++']]
[['Python' 'Php' 'Java' 'C++']]
[['PYTHON' 'pHP' 'jAVA' 'c++']]


In [144]:
# print data type
a.dtype

dtype('<U6')

In [145]:
# program to make the length of elements 15 elements 
a = np.array([['python', 'Php', 'Java', 'C++']])
centered = np.char.center(a, 15, fillchar='_')
leftJustified = np.char.ljust(a, 15, fillchar='_')
rightJustified = np.char.rjust(a, 15, fillchar='_')
print(centered)
print(leftJustified)
print(rightJustified)

[['_____python____' '______Php______' '______Java_____' '______C++______']]
[['python_________' 'Php____________' 'Java___________' 'C++____________']]
[['_________python' '____________Php' '___________Java' '____________C++']]


In [132]:
# program to insert a space between characters 
a = np.array([['python', 'Php', 'Java', 'C++']])
b = np.char.join('*', a)# * is called sep or seperator
b

array([['p*y*t*h*o*n', 'P*h*p', 'J*a*v*a', 'C*+*+']], dtype='<U11')

In [150]:
date = '19 08 2022'
date

'19 08 2022'

In [152]:
date.replace(' ', '-')

'19-08-2022'

In [154]:
np.char.join('/', date)

array('1/9/ /0/8/ /2/0/2/2', dtype='<U19')

In [156]:
np.char.split(date)

array(list(['19', '08', '2022']), dtype=object)

In [157]:
# remove leading and trailing whitespaces of all elements in a given array
a = np.array([' python ', ' PHP ', ' Java ', ' C++ '])
b = np.char.split(a)
print(b)

[list(['python']) list(['PHP']) list(['Java']) list(['C++'])]


In [158]:
# split array elements
a = np.array(['python Php Java C++'])
print(np.char.split(a))

[list(['python', 'Php', 'Java', 'C++'])]


In [159]:
# split elements to multiple lines
a = np.array(['Python/exercises, Practice, solution'])
print(np.char.split(a))
print(np.char.splitlines(a))

[list(['Python/exercises,', 'Practice,', 'solution'])]
[list(['Python/exercises, Practice, solution'])]


In [160]:
# program of string with 5 digits with zeros on the left
x = np.array(['2', '34','123', '3456'])
print(np.char.zfill(x,5))

['00002' '00034' '00123' '03456']


In [161]:
# replace
a = np.array(['Python exercises, Practice, solution'])
replace = np.char.replace(a,'Python', 'PHP')
print(replace)

['PHP exercises, Practice, solution']


In [162]:
# np.char.count used to count the number of the selected element in an array
x = np.array(['Python', 'PHP', 'JS', 'EXAMPLES'])
print(np.char.count(x, 'P'))
print(np.char.find(x, 'P')) # returns the lowest index of occurence of an element

[1 2 0 1]
[ 0  0 -1  4]


## np.char.isdigit checks if the given elements are digits and returns a boolean
### np.char.isupper checks if the given elements are in upper case and returns a boolean as well
### np.char.islower checks for lower case and returns a boolean value
### np.char.startswith checks whether an array starts with a certain character and returns a boolean

In [ ]:
# to add zeros
num = np.array(['1.12', '2.23', '3.71', '4.23'])
print(np.char.zfill(num, 6))
print(np.char.add('00', num))
print(np.char.rjust(num, 6, fillchar='0'))

In [ ]:
# array to replace a specific character with another 
x = np.array([['Python-numpy-exercise'],['-Python-']])
y = np.char.replace(x, '-', '=')
z = np.char.replace(y, '=', ' ')
print(x)
print(y)
print(z)
print(np.char.split(y))
print(np.char.splitlines(z))

## statistics

In [163]:
# find minimum and maximum of a given array
a = np.arange(1,5).reshape(2,2)
min = np.min(a, axis=1)
print(a)
print(min)
print(np.max(a))

[[1 2]
 [3 4]]
[1 3]
4


In [164]:
b = np.empty(2, dtype='int')
b

array([321099904,     32762])

In [165]:
b = np.empty((2,2), dtype='int')
b

array([[-1485105776,         508],
       [          0,           0]])

In [166]:
# view and copy
a = np.array([1,2,3,4])

# create a copy and a view
c = a.copy()
v = a.view()

# to find whether an array owns the data
print(c.base)
print(v.base)

None
[1 2 3 4]


In [167]:
# copying a numpy array into another numpy array
### use functions: np.empty_like, np.copy and assignment operator 
a = np.array([1,2,3,4])
print(np.empty_like(a))
print(np.copy(a))
b = a 
print(b)

[-1485105776         508           0           0]
[1 2 3 4]
[1 2 3 4]


In [168]:
# combining one and a two dimensional array
arr1 = np.arange(5)
arr2 = np.arange(10).reshape(2,5)

for a,b in np.nditer([arr1, arr2]):
    print('%d: %d', (a,b))

%d: %d (array(0), array(0))
%d: %d (array(1), array(1))
%d: %d (array(2), array(2))
%d: %d (array(3), array(3))
%d: %d (array(4), array(4))
%d: %d (array(0), array(5))
%d: %d (array(1), array(6))
%d: %d (array(2), array(7))
%d: %d (array(3), array(8))
%d: %d (array(4), array(9))


In [176]:
#numpy manipulation
# use functions such as add(), subtract(), divide(), multiply() for elementwise calculations and dot() for matrix multiplication
# use sum(), sqrt(), and T for transpose
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print('PRINTING A')
print(a)
print()

print('PRINTING B')
print(b)
print()

print('ADD')
print(np.add(a,b))
print()

print('SUBTRACT')
print(np.subtract(a,b))
print()

print('DIVIDE')
print(np.divide(a,b))
print()

print('MULTIPLY')
print(np.multiply(a,b))
print()

print('DOT MULTIPLY')
print(np.dot(a,b))
print()

print('A TRANSPOSE')
print(a.T)
print()

print(np.sum(a))
print(np.sqrt(a))

PRINTING A
[[1 2]
 [3 4]]

PRINTING B
[[5 6]
 [7 8]]

ADD
[[ 6  8]
 [10 12]]

SUBTRACT
[[-4 -4]
 [-4 -4]]

DIVIDE
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

MULTIPLY
[[ 5 12]
 [21 32]]

DOT MULTIPLY
[[19 22]
 [43 50]]

A TRANSPOSE
[[1 3]
 [2 4]]

10
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [182]:
one = np.array([1,2,3])
two = np.array([[1,2,4], [3,4,5]])

print(one)
print()
print(two)

np.multiply(one, two)

[1 2 3]

[[1 2 4]
 [3 4 5]]


array([[ 1,  4, 12],
       [ 3,  8, 15]])

In [183]:
# np.dot(one, two)

In [193]:
# compute eigen values
b = np.array([[5,6], [7,8]])
print(np.linalg.eigvals(b))

[-0.15206735 13.15206735]


In [192]:
# compute variance of a matrix
b = np.array([5,6])
print(np.var(b))

0.25


In [191]:
# inverse of a matrix
b = np.array([[5,6], [7,8]])
print(np.linalg.inv(b))

[[-4.   3. ]
 [ 3.5 -2.5]]


In [190]:
# np.split returns a list of strings after breaking the given string by a specified seperator(sep) or delimiter
print(np.char.split('geeks for geeks'), sep='-')

['geeks', 'for', 'geeks']


In [189]:
# np.join is a string method that returns a string in wich the elemnts of a sequence have joined by str seperator
print(np.char.join('-', 'geeks'))
print(np.char.join(['-', ':'], ['geeks', 'for']))

g-e-e-k-s
['g-e-e-k-s' 'f:o:r']


In [185]:
# np.strip/lstrip/rstrip is used to remove all the leading and trailing spaces from a string
str = '-----geeksforgeeks--------'
print(str)
print(str.strip('-'))
print(str.rstrip('-'))
print(str.lstrip('-'))

-----geeksforgeeks--------
geeksforgeeks
-----geeksforgeeks
geeksforgeeks--------


In [188]:
# replace a string
str = 'nerds for nerds'
print(str.replace('nerds', 'geeks'))


geeks for geeks


### np.count function returns the number of occrurences of a substring in the given string
### np.find function returns the lowetst index of the substring in a given string. If not found it gives -1
### np.isnumeric function returns True if all characters are numeric characters otherwise false
### np.index function returns position of the first occurence of substring in a string
### np.isalpha fuction returns true if all characters in the string are alphabets otherwise false
### np.isdecimal returns true if all characters in a string are decimal
### np.isdigit if digits in a string returns true
### np.startswith fucntion returns true if a string starts with the given prefix otherwise false
### np.isupper, islower, istitle functions work the same
### np.equal, not_equal, greater, greater_equal, less_equal, less functions compare strings 

In [187]:
# flatten 
a = np.array([[1,2,3], [4,5,6]])
print(a)
print()
# flatten to 1-D array/matrix
print(a.flatten())

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
